export interface InputProps {
    name?: string,
    id?: string,
    icon?: string,
    error?: string | boolean,
    required?: boolean,
    toggle?: boolean,
    type?: string,
    label?: string,
    placeholder?: string,
    value?: string,
    helperText?: string,
    spacing?: boolean,
    onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void,
    onBlur?: (e: React.FocusEvent<HTMLInputElement>) => void,
    onFocus?: (e: React.FocusEvent<HTMLInputElement>) => void,
    onKeyDown?: (e: React.KeyboardEvent<HTMLInputElement>) => void,
    onKeyUp?: (e: React.KeyboardEvent<HTMLInputElement>) => void,
    onKeyPress?: (e: React.KeyboardEvent<HTMLInputElement>) => void,
    onClick?: (e: React.MouseEvent<HTMLInputElement>) => void,
    onDoubleClick?: (e: React.MouseEvent<HTMLInputElement>) => void,
    onContextMenu?: (e: React.MouseEvent<HTMLInputElement>) => void,
    onMouseDown?: (e: React.MouseEvent<HTMLInputElement>) => void,
    onMouseUp?: (e: React.MouseEvent<HTMLInputElement>) => void,
    onMouseEnter?: (e: React.MouseEvent<HTMLInputElement>) => void,
    onMouseLeave?: (e: React.MouseEvent<HTMLInputElement>) => void,
    onMouseOver?: (e: React.MouseEvent<HTMLInputElement>) => void,
    onMouseOut?: (e: React.MouseEvent<HTMLInputElement>) => void,
    onMouseMove?: (e: React.MouseEvent<HTMLInputElement>) => void,
    onDragStart?: (e: React.DragEvent<HTMLInputElement>) => void,
    onDragEnd?: (e: React.DragEvent<HTMLInputElement>) => void,
    onDragEnter?: (e: React.DragEvent<HTMLInputElement>) => void,
}