export const EmailIcon = "las la-envelope"
export const HidePasswordIcon = "las la-eye-slash"
export const ShowPasswordIcon = "las la-eye"
export const PasswordIcon = "las la-key"
export const PasswordIconAlt = "las la-unlock-alt"
export const PasswordResetSuccess = "las la-check-circle"